Repository codeandtheory/ybottomsheet-ios, pull requests merged in 2023-03, with the labels that each got.

#10 [Issue 9] Hide pull request template
  .github/pull_request_template.md
  README.md
Labels: cleanup

#12 [CM-1244] Dependencies section added to read me.
  README.md
Labels: enhancement

#15 [CM-1243] Support for reduce motion accessibility.
  Package.swift
  Sources/YBottomSheet/Animation/BottomSheetAnimator.swift
  Sources/YBottomSheet/Animation/BottomSheetDismissAnimator.swift
  Sources/YBottomSheet/Animation/BottomSheetPresentAnimator.swift
  Tests/YBottomSheetTests/Animation/BottomSheetDismissAnimatorTests.swift
  Tests/YBottomSheetTests/Animation/BottomSheetPresentAnimatorTests.swift
Labels: enhancement, A11y

#17 [Issue 16] Fix corner radius bug
  Sources/YBottomSheet/BottomSheetController.swift
  Tests/YBottomSheetTests/BottomSheetControllerTests.swift
Labels: bug
